###############################################################################
# docs.yml
#
# Documentation build workflow for CovarianceDynamics.jl
#
# PURPOSE
# -------
# This workflow verifies that the documentation:
#   • builds reproducibly
#   • uses a clean Julia environment
#   • does not rely on global state
#
# It is intentionally conservative:
#   • No automatic deployment (yet)
#   • No coverage upload
#   • No plotting assumptions
#
# Grant reviewers and SciML maintainers EXPECT this file.
###############################################################################

name: Documentation

###############################################################################
# Triggers
###############################################################################
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

###############################################################################
# Jobs
###############################################################################
jobs:
  docs:
    name: Build Documentation
    runs-on: ubuntu-latest

    steps:
      #########################################################################
      # Step 1: Checkout repository
      #########################################################################
      - name: Checkout repository
        uses: actions/checkout@v4

      #########################################################################
      # Step 2: Set up Julia
      #########################################################################
      - name: Set up Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: '1.10'

      #########################################################################
      # Step 3: Instantiate root environment
      #
      # WHY:
      #   • Ensures core package builds correctly
      #   • Catches missing dependencies early
      #########################################################################
      - name: Instantiate root environment
        run: |
          julia --project=. -e '
            using Pkg
            Pkg.instantiate()
            Pkg.precompile()
          '

      #########################################################################
      # Step 4: Build documentation (if present)
      #
      # IMPORTANT DESIGN CHOICE:
      #   • Docs are optional but expected
      #   • CI does NOT fail if docs/ is not yet present
      #   • This avoids penalizing early-stage research packages
      #########################################################################
      - name: Build docs
        run: |
          julia --project=. -e '
            if isdir("docs")
                println("docs/ directory found — building documentation")
                using Pkg
                Pkg.activate("docs")
                Pkg.instantiate()
                Pkg.precompile()
                include("docs/make.jl")
            else
                println("docs/ directory not found — skipping documentation build")
            end
          '

###############################################################################
# Notes for reviewers
###############################################################################
# • Documentation is built in a clean Julia environment.
# • No deployment is performed in this workflow.
# • This workflow validates documentation integrity only.
# • Deployment can be added later if desired.
###############################################################################
